eea/volto-arcgis-block

src/components/MapViewer/BasemapWidget.jsx
src/components/MapViewer/MenuWidget.jsx
src/components/MapViewer/css/ArcgisMap.css

Map styles

---

src/components/MapViewer/MenuWidget.jsx
src/components/MapViewer/config.js

Active by default layers, datasets and products

Active by default

---

src/components/MapViewer/MenuWidget.jsx

* The area object changed to a valid json:
https://github.com/eea/volto-arcgis-block/compare/develop...add-cart-items-improvements?expand=1#diff-0fbe148cb3aa4aa86aa2310bf4c9479b6325f96a1c8843bac7a41ca49df42801R30
With the changes, the area will return an object like this:
From: 
```JSON
[{
"id": "0407d497d3c44bcd93ce8fd5bf78596a",
"UID": "0407d497d3c44bcd93ce8fd5bf78596a",
"unique_id": "0407d497d3c44bcd93ce8fd5bf78596a-1640086702506",
"area": [
"type": "polygon",
"value": [
524.389892578125,
212.8692626953125,
635.50341796875,
320.6351318359375
]
]
}]
```
To: 
```JSON
[{
"id": "0407d497d3c44bcd93ce8fd5bf78596a",
"UID": "0407d497d3c44bcd93ce8fd5bf78596a",
"unique_id": "0407d497d3c44bcd93ce8fd5bf78596a-1640086702506",
"area": {
"type": "polygon",
"value": [
524.389892578125, …
```

The area array to a json object and added a unique_id to the cart

---

src/components/MapViewer/MapViewer.jsx
src/components/MapViewer/MenuWidget.jsx

Reverts eea/volto-arcgis-block#147

Revert "Mapviewer menu and map viewer options persistence"

---

cypress.json

Reverts eea/volto-arcgis-block#154

Revert "MapViewer persistence implemented"

---

src/components/MapViewer/MenuWidget.jsx
src/components/MapViewer/TimesliderWidget.jsx
src/components/MapViewer/css/ArcgisMap.css

Time slider. Now allows entering start date and end date.
Privacy popup. Updated to use the same color as the rest of the app.

time slider + privacy popup updates

---

src/components/MapViewer/MenuWidget.jsx

Changes to show login popup after clicking on the download icon of the TOC menu. (as non-logged in user)

CLMS-1614. Login popup after click download.

---

src/components/MapViewer/MenuWidget.jsx

Completed the corrections for the 1635 ticket (fix popup message for download requests).

Popup message

---

src/components/MapViewer/MenuWidget.jsx

Changed value in the comparison to correctly reflect the state needed for the alert to show.

CLMS-1700 refactor: changed key comparison to reflect correct value

---

src/components/MapViewer/MenuWidget.jsx
src/components/MapViewer/css/ArcgisMap.css

Fixed interaction bug with select area widget.

Select area widget bug fixed

---

src/components/MapViewer/MenuWidget.jsx

CLMS-1633 fix: Changed success to Success. Hid the timer bar.

CLMS-1633 fix: Changed success to Success. Hid the timer bar.

---

src/components/MapViewer/MenuWidget.jsx

CLMS-1633 fix: Corrected titles for toast popups on download

CLMS-1633 fix: Corrected titles for toast popups on download

---

src/components/MapViewer/HotspotWidget.jsx
src/components/MapViewer/MenuWidget.jsx

fix: hotspot functions on reload correctly.

Clms 1581 hotspot

---

src/components/MapViewer/MenuWidget.jsx

Reverts eea/volto-arcgis-block#318

Revert "CLMS-1634 (FIX): Show Zoom message in Snow and Ice datasets"

---

src/components/MapViewer/BasemapWidget.jsx
src/components/MapViewer/MapViewer.jsx
src/components/MapViewer/config.js

Limit extent

---

src/components/MapViewer/MenuWidget.jsx

Zoom in message for snow product and datasets works again. Download button is displayed again.

CLMS-2369 (bug)

---

src/components/MapViewer/MenuWidget.jsx

CLMS-2369 (fix): relevant bug is fixed now for snow and ice pop up message

---

src/components/MapViewer/HotspotWidget.jsx

They will remain selected in their drop down menus as long as selected region exists in new layer options

CLMS-2422 (bug): year filter selections persist past layer changes

---

src/components/MapViewer/HotspotWidget.jsx
src/components/MapViewer/LegendWidget.jsx
src/components/MapViewer/MapViewer.jsx
src/components/MapViewer/MenuWidget.jsx

Fixed:
- Prevent SessionStorage Clearance on Login with Referrer URLs.
- The hotspot filter form is reset when the user selects layers from another product.
- The dichotomous hotspots layers change to modular hotspot when the user selects another layer from Reference Land Cover.
- Implement Dynamic Legends for MapViewer.

Clms hotspot bug fixes

---

src/components/MapViewer/MenuWidget.jsx

… information icon links to localhost in demo environment

CLMS-2916 info icon points to localhost

---

src/components/MapViewer/AreaWidget.jsx
src/components/MapViewer/HotspotWidget.jsx
src/components/MapViewer/InfoWidget.jsx
src/components/MapViewer/LoadingSpinner.jsx
src/components/MapViewer/MapViewer.jsx
src/components/MapViewer/MenuWidget.jsx
src/components/MapViewer/PrintWidget.jsx
src/components/MapViewer/ScaleWidget.jsx
src/components/MapViewer/SwipeWidget.jsx

Patch disabling lazy loading for info widget.

CLMS-DATA-VIEWER-CRASH-PATCH (BUG)

---

src/components/MapViewer/MenuWidget.jsx

CLMS-270893 (bug): Fixed scroll positioning of checked dataset in dat…aviewer when coming from dataset catalogue result

CLMS-270893 (bug): Fixed scroll positioning

---

src/components/MapViewer/AreaWidget.jsx
src/components/MapViewer/MapViewer.jsx
src/components/MapViewer/MenuWidget.jsx
src/components/MapViewer/UploadWidget.jsx

Tickets:
CLMS-286081: The datasets loaded in "My service" are lost when the user logs out and logs in again.
CLMS-286065: The checkbox of the other dataset unchecks when the user removes one of the "My Service" datasets.
CLMS-286043: My Service does not load properly after uploading a duplicated layer.
CLMS-286148: The area selection controls hide the "Add map services" button when activated.

Clms 250331 batch ticket upload

---

src/components/MapViewer/BookmarkWidget.jsx

CLMS-287785 (bug): all bookmark data updated on order shift
CLMS-286086 (bug): order upon arriving persistence fixed

CLMS-287785-286086 (bug)

---

src/components/MapViewer/MenuWidget.jsx

Fixed hardcoded value in fetch request byoc collection id's and service endpoints become are inyected into request programmatically now

(bug): fixed hardcoded value in fetch request

---

src/components/MapViewer/TimesliderWidget.jsx

(bug): The time slider doesn't load when the web service URL is in proxy format. FIXED

CLMS-292477

---

src/components/MapViewer/BookmarkWidget.jsx

Organize and save bookmark data inside user-id object in localstorage

Clms 292637
